version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APP_ENV=${APP_ENV}
        container_name: app
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www:delegated
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db
        networks:
            - app-network

    webserver:
        image: nginx:1.23.3-alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www:delegated
            - ./docker/nginx/conf.d/dev/:/etc/nginx/conf.d/  # Mounts the directory for Nginx conf.d
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf  # Mounts the Nginx main config file
        networks:
            - app-network

    db:
        image: mariadb:10.5.8
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT}:3306"  # Ensure DB_PORT from .env is mapped correctly
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"



    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        tty: true
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-9191}:80'
        environment:
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: db       # Ensure this matches your db service name
            PMA_PORT: 3308      # Match your DB_PORT
            SERVICE_NAME: phpmyadmin
        networks:
            - app-network
        depends_on:
            - db


networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
    nginx-config:
        driver: local
